# clisp-link
# Autogenerated from man page /usr/local/share/man/man1/clisp-link.1
# using Deroffing man parser
complete -c clisp-link -l without-dynamic-modules --description 'SYS::DYNLOAD-MODULES.'

