# clisp
# Autogenerated from man page /usr/local/share/man/man1/clisp.1
# using Deroffing man parser
complete -c clisp -o 'h
.br
--help' --description 'Displays a help message on how to invoke \\m[blu… [See Man Page]'
complete -c clisp -l version --description 'Displays the \\m[blue]CLISP\\m[]\\s-2\\u[6]\\d\\s+2 v… [See Man Page]'
complete -c clisp -l license --description 'Displays a summary of the licensing information… [See Man Page]'
complete -c clisp -o help-image --description 'Displays information about the memory image bei… [See Man Page]'
complete -c clisp -s B --description 'Specifies the installation directory.'
complete -c clisp -s b --description 'Print the installation directory and exit immediately.'
complete -c clisp -s M --description 'Specifies the initial memory image.'
complete -c clisp -s L --description 'Specifies the language \\m[blue]CLISP\\m[]\\s-2\\u[… [See Man Page]'
complete -c clisp -s N --description 'Specifies the base directory of locale files.'
complete -c clisp -o 'q
.br
--quiet
.br
--silent
.br
-v
.br
--verbose' --description 'Change verbosity level: by default, \\m[blue]CLI… [See Man Page]'
complete -c clisp -o repl --description 'Start an interactive \\m[blue]read-eval-print lo… [See Man Page]'
complete -c clisp -s w --description 'Wait for a keypress after program termination.'
complete -c clisp -s I --description 'Interact better with \\m[blue]Emacs\\m[]\\s-2\\u[23… [See Man Page]'
complete -c clisp -o disable-readline --description 'Do not use \\m[blue]GNU\\m[]\\s-2\\u[8]\\d\\s+2 \\m[bl… [See Man Page]'
complete -c clisp -o ansi --description 'Comply with the [ANSI CL standard] specificatio… [See Man Page]'
complete -c clisp -o traditional --description 'Traditional: reverses the residual effects of -… [See Man Page]'
complete -c clisp -o modern --description 'Provides a modern view of symbols: at startup t… [See Man Page]'
complete -c clisp -s p --description 'At startup the value of the variable \\m[blue]*P… [See Man Page]'
complete -c clisp -s C --description 'Compile when loading: at startup the value of t… [See Man Page]'
complete -c clisp -o norc --description 'Normally \\m[blue]CLISP\\m[]\\s-2\\u[6]\\d\\s+2 loads… [See Man Page]'
complete -c clisp -o lp --description 'Specifies directories to be added to CUSTOM:*LO… [See Man Page]'
complete -c clisp -s i --description 'Specifies initialization files to be \\m[blue]LO… [See Man Page]'
complete -c clisp -s c --description 'Compiles the specified lisp-files to bytecode (*. fas).'
complete -c clisp -s o --description 'Specifies the output file or directory for the … [See Man Page]'
complete -c clisp -s l --description 'Produce a bytecode \\m[blue]DISASSEMBLE\\m[]\\s-2\\… [See Man Page]'
complete -c clisp -s x --description 'Executes a series of arbitrary expressions inst… [See Man Page]'
complete -c clisp -s h --description '.'
complete -c clisp -l help --description '.'
complete -c clisp -s K --description '.'
complete -c clisp -s m --description '.'
complete -c clisp -o Edomain --description '.'
complete -c clisp -s q --description '.'
complete -c clisp -l quiet --description '.'
complete -c clisp -l silent --description '.'
complete -c clisp -s v --description '.'
complete -c clisp -l verbose --description '.'
complete -c clisp -o 'v.' --description '.'
complete -c clisp -o on-error --description '.'
complete -c clisp -l 'm[blue]John' --description 'When m[blue]CLISPm[]\\u[6]\\d is invoked, the run… [See Man Page]'

