# emacsclient
# Autogenerated from man page /usr/share/man/man1/emacsclient.1
# using Deroffing man parser
complete -c emacsclient -s h --description 'print this usage information message and exit S… [See Man Page]'

