# git-rev-parse
# Autogenerated from man page /usr/local/share/man/man1/git-rev-parse.1
# using Deroffing man parser
complete -c git-rev-parse -l stuck-long --description 'Only meaningful in --parseopt mode.'
complete -c git-rev-parse -l exclude --description 'Do not include refs matching <glob-pattern> tha… [See Man Page]'
complete -c git-rev-parse -l branches --description '.'
complete -c git-rev-parse -l tags --description '.'
complete -c git-rev-parse -l remotes --description '.'
complete -c git-rev-parse -l 'all.' --description '/* is intended, it must be given explicitly.'

