# git-fetch
# Autogenerated from man page /usr/local/share/man/man1/git-fetch.1
# using Deroffing man parser
complete -c git-fetch -l update-shallow --description 'By default when fetching from a shallow reposit… [See Man Page]'
complete -c git-fetch -l 'prune).' --description '.'

