# git-config
# Autogenerated from man page /usr/local/share/man/man1/git-config.1
# using Deroffing man parser
complete -c git-config -o 'c.' --description 'LV with another value or setting core. pager to lv +c.  core.'
complete -c git-config -s O --description 'option to git-diff(1).  diff. renameLimit.'
complete -c git-config -l pack-kept-objects --description 'was passed.  See git-repack(1) for details.'
complete -c git-config -l write-bitmap-index --description 'or pack. writeBitmaps).  rerere. autoupdate.'

