# git-log
# Autogenerated from man page /usr/local/share/man/man1/git-log.1
# using Deroffing man parser
complete -c git-log -l exclude --description 'Do not include refs matching <glob-pattern> tha… [See Man Page]'
complete -c git-log -l 'show-linear-break[' --description 'When --graph is not used, all history branches … [See Man Page]'
complete -c git-log -l branches --description '.'
complete -c git-log -l tags --description '.'
complete -c git-log -l remotes --description '.'
complete -c git-log -l 'all.' --description '/* is intended, it must be given explicitly.'
complete -c git-log -l 'no-walk.' --description '.'
complete -c git-log -l 'pretty.' --description 'log.'
complete -c git-log -o 'O/dev/null.' --description '.'

