# git-pull
# Autogenerated from man page /usr/local/share/man/man1/git-pull.1
# using Deroffing man parser
complete -c git-pull -l update-shallow --description 'By default when fetching from a shallow reposit… [See Man Page]'

