# git-merge-base
# Autogenerated from man page /usr/local/share/man/man1/git-merge-base.1
# using Deroffing man parser
complete -c git-merge-base -l fork-point --description '.'
complete -c git-merge-base -l -o---o---B2--o---o---o---B --description '        \\          B3           \\            De… [See Man Page]'

