# git-filter-branch
# Autogenerated from man page /usr/local/share/man/man1/git-filter-branch.1
# using Deroffing man parser
complete -c git-filter-branch -l strip-blobs-bigger-than --description '.'

