# git-replace
# Autogenerated from man page /usr/local/share/man/man1/git-replace.1
# using Deroffing man parser
complete -c git-replace -l format --description 'When listing, use the specified <format>, which… [See Man Page]'

