# git-rebase
# Autogenerated from man page /usr/local/share/man/man1/git-rebase.1
# using Deroffing man parser
complete -c git-rebase -o 'S[<keyid>]' -l 'gpg-sign[' --description 'GPG-sign commits.'
complete -c git-rebase -l fork-point -l no-fork-point --description 'Use git merge-base --fork-point to find a bette… [See Man Page]'

