# git-rev-list
# Autogenerated from man page /usr/local/share/man/man1/git-rev-list.1
# using Deroffing man parser
complete -c git-rev-list -l exclude --description 'Do not include refs matching <glob-pattern> tha… [See Man Page]'
complete -c git-rev-list -l use-bitmap-index --description 'Try to speed up the traversal using the pack bi… [See Man Page]'
complete -c git-rev-list -l 'show-linear-break[' --description 'When --graph is not used, all history branches … [See Man Page]'
complete -c git-rev-list -l branches --description '.'
complete -c git-rev-list -l tags --description '.'
complete -c git-rev-list -l remotes --description '.'
complete -c git-rev-list -l 'all.' --description '/* is intended, it must be given explicitly.'
complete -c git-rev-list -l 'no-walk.' --description '.'
complete -c git-rev-list -l 'pretty.' --description 'log.'

