# grep-changelog
# Autogenerated from man page /usr/local/share/man/man1/grep-changelog.1.gz
# using Deroffing man parser
complete -c grep-changelog -l author --description 'Print entries whose author matches regular expr… [See Man Page]'
complete -c grep-changelog -l text --description 'Print entries whose text matches regular expression R TEXT .'
complete -c grep-changelog -l exclude --description 'Exclude entries matching regular expression R TEXT .'
complete -c grep-changelog -l from-date --description 'Only consider entries made on or after the given date.'
complete -c grep-changelog -l to-date --description 'Only consider entries made on or before the given date.'
complete -c grep-changelog -l rcs-log --description 'Print output in a format suitable for RCS log entries.'
complete -c grep-changelog -l with-date --description 'In RCS log format, print short dates.'
complete -c grep-changelog -l reverse --description 'Show matches in reverse order.'
complete -c grep-changelog -l version --description 'Display version information.'
complete -c grep-changelog -l help --description 'Display basic usage information.'

