# tor
# Autogenerated from man page /usr/local/share/man/man1/tor.1
# using Deroffing man parser
complete -c tor -s h -o help --description '.'
complete -c tor -s f --description '.'
complete -c tor -l defaults-torrc --description '.'
complete -c tor -l hash-password --description '.'
complete -c tor -l list-fingerprint --description '.'
complete -c tor -l verify-config --description '.'
complete -c tor -l service --description '.'
complete -c tor -l nt-service --description '.'
complete -c tor -l list-torrc-options --description '.'
complete -c tor -l version --description '.'
complete -c tor -l quiet -l hush --description '.'

