# typefortune
# Autogenerated from man page /usr/local/share/man/man1/typefortune.1
# using Deroffing man parser
complete -c typefortune -s d --description '.'
complete -c typefortune -s s -o 's\'' --description '.'
complete -c typefortune -s l -o 'l\'' --description '.'
complete -c typefortune -s n --description '.'
complete -c typefortune -s o --description 'EXAMPLE To practice 3 fortunes and run gtypist … [See Man Page]'

