require("configs.plugins")
require('configs.options')
require("configs.colorscheme")
require("configs.keymaps")

require("configs.mason")
require("configs.lspconfig")
require("configs.rust-tools")
require("configs.rubocop-lsp")
require("configs.ruby-lsp")
require("configs.telescope")

require("configs.treesitter")
require("configs.trouble")
require("configs.lualine")
